# This is a basic workflow to help you get started with Actions

name: Linter

on: push

jobs:
  lint:
    name: Lint Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Lint debug
        run: ./gradlew lint --stacktrace
      
      - name: Lint results
        uses: actions/upload-artifact@v2.2.2
        with:
          name: app
          path: app/build/reports/lint-results.html
